version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    ports:
      - "3000:3000"
    working_dir: /frontend
    command: serve -s build -l 3000

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
    ports:
      - "5000:5000"
    working_dir: /backend
    command: node index.js 
