version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    ports:
      - "80:80"
    working_dir: /frontend
    command: npm start

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
    ports:
      - "5000:5000"
    working_dir: /backend
    command: node --env-file=./.env index.js
